### ISSUE TITLE
[BUG] NbtApiException is thrown on newer versions like 1.20.2

### ISSUE THREAD

**Issue by Supermarcel10** [ItsTonus/HatCosmetics#2]
An exception occurs on startup utilising v1.2.0-b5 with NBT-API 2.11.3 and Paper 1.20.2 ([9271ee7](https://github.com/PaperMC/paper/commit/9271ee7643614663a6d93323a9e8db2d52123166))

![image](https://github.com/ItsTonus/HatCosmetics/assets/47798787/369d695c-ae84-47be-b454-ac16a2296cec)
[Pastebin of Error](https://pastebin.com/uAFwAgwu)

**Comment by ItsTonus** [comment]
Yeah, that's happening because it's using a version of NBT-API that doesn't support NMS for 1.20.2.

I could just update the plugin with the latest version of NBT-API, but since this has become the only reason for plugin updates now, I would like to stop shading the API into the plugin and just have sever developers update it themselves.

I started looking into making this change, but I ran into issues I couldn't figure out and would have to continue investigating.

**Comment by Supermarcel10** [comment]
I'm already working on a potential fix, and will make a PR in the next few mins.

**Comment by Supermarcel10** [comment]
This still causes a warning, but is a temporary ostrich solution.

[21:55:23 WARN]: [NBTAPI] #########################################- NBTAPI -#########################################
[21:55:23 WARN]: [NBTAPI] The NBT-API inside HatCosmetics is the plugin version, not the API!
[21:55:23 WARN]: [NBTAPI] The plugin itself should never be shaded! Remove the `-plugin` from the dependency and fix your shading setup.
[21:55:23 WARN]: [NBTAPI] For more info check: https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven#option-2-shading-the-nbt-api-into-your-plugin
[21:55:23 WARN]: [NBTAPI] #########################################- NBTAPI -#########################################

**Comment by ItsTonus** [comment]
> This still causes a warning, but is a temporary ostrich solution.
> 
> [21:55:23 WARN]: [NBTAPI] #########################################- NBTAPI -######################################### [21:55:23 WARN]: [NBTAPI] The NBT-API inside HatCosmetics is the plugin version, not the API! [21:55:23 WARN]: [NBTAPI] The plugin itself should never be shaded! Remove the `-plugin` from the dependency and fix your shading setup. [21:55:23 WARN]: [NBTAPI] For more info check: https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven#option-2-shading-the-nbt-api-into-your-plugin [21:55:23 WARN]: [NBTAPI] #########################################- NBTAPI -#########################################

Based on what [this](https://github.com/tr7zw/Item-NBT-API/wiki/Using-Gradle#option-2-shading-the-nbt-api-into-your-plugin) is saying and what build.gradle looks like, looks like line 33 of build.gradle may need to be changed to `relocate('de.tr7zw.changeme.nbtapi', 'me.Tonus_.hatCosmetics.libs.nbt-api')` to fix that. That's the only real difference I could find in how the API is currently being shaded.

**Comment by Supermarcel10** [comment]
I've made a push to the PR and it seems the warning is also now gone, from basic testing the plugin seems to be working as normal.

**Comment by Supermarcel10** [comment]
Closed as implemented in #3
